// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi1ccYw2EZg1jQv76yX0EhpEwtbtHMA-k',
    appId: '1:734667582724:web:fd1096d23130d2ffa63451',
    messagingSenderId: '734667582724',
    projectId: 'tiva-2f341',
    authDomain: 'tiva-2f341.firebaseapp.com',
    storageBucket: 'tiva-2f341.firebasestorage.app',
    measurementId: 'G-8RETL81N28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCozwCqz2V6lt7uiQJpIwa14azEPkTkEnM',
    appId: '1:734667582724:android:bd7f60071be54aa2a63451',
    messagingSenderId: '734667582724',
    projectId: 'tiva-2f341',
    storageBucket: 'tiva-2f341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIn8tMWM9pFFhpC5d7UsNZ2pUBRUWgUOc',
    appId: '1:734667582724:ios:facb2e4fba9190dba63451',
    messagingSenderId: '734667582724',
    projectId: 'tiva-2f341',
    storageBucket: 'tiva-2f341.firebasestorage.app',
    iosClientId: '734667582724-ekgbgvh5573umage343el8urasrb2gsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIn8tMWM9pFFhpC5d7UsNZ2pUBRUWgUOc',
    appId: '1:734667582724:ios:facb2e4fba9190dba63451',
    messagingSenderId: '734667582724',
    projectId: 'tiva-2f341',
    storageBucket: 'tiva-2f341.firebasestorage.app',
    iosClientId: '734667582724-ekgbgvh5573umage343el8urasrb2gsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi1ccYw2EZg1jQv76yX0EhpEwtbtHMA-k',
    appId: '1:734667582724:web:e846dbf4717dba9ca63451',
    messagingSenderId: '734667582724',
    projectId: 'tiva-2f341',
    authDomain: 'tiva-2f341.firebaseapp.com',
    storageBucket: 'tiva-2f341.firebasestorage.app',
    measurementId: 'G-MRNGZZWCR8',
  );
}
